export const SHOW_ALL = 'SHOW_ALL';
export const SHOW_COMPLETED = 'SHOW_COMPLETED';
export const SHOW_ACTIVE = 'SHOW_ACTIVE';
export const ADD_TODO = 'ADD_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const REMOVE_COMPLETED = 'REMOVE_COMPLETED';
export const TOGGLE_TODO_STATUS = 'TOGGLE_TODO_STATUS';

export const SET_STATUS_FILTER_SHOW_ALL = 'SET_STATUS_FILTER_SHOW_ALL';
export const SET_STATUS_FILTER_SHOW_COMPLETED = 'SET_STATUS_FILTER_SHOW_COMPLETED';
export const SET_STATUS_FILTER_SHOW_ACTIVE = 'SET_STATUS_FILTER_SHOW_ACTIVE';
export const SET_SEARCH_TEXT_FILTER = 'SET_SEARCH_TEXT_FILTER';
